# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda_compiler_version:
  - 12.4

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake:
  - ">=3.28"

python:
  - 3.9
  - 3.10
  - 3.11
