# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: numbast-cu13
channels:
  - numba
  - conda-forge
  - nvidia
dependencies:
  - python>=3.10
  - cmake>=3.29 # Allow overriding CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX
  - clangdev >=18,<22.0
  - numba-cuda[cu13] >=0.21.0,<0.23.0
  - numpy<2.4
  - pybind11
  - pytest
  - pytest-benchmark
  - cffi
  - mypy
  - pre-commit
  - cxx-compiler
  - cuda-version=13.0
  - cuda-toolkit=13.0
  - cuda-python=13.0
  - scikit-build-core
  - pip
  - ninja
  - pyyaml
  - ruff
  - click
  - jinja2
  - sphinx
  - sphinx-copybutton
  - pip:
      - nvidia-sphinx-theme
