# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: CI
on:
  push:
    branches:
      - "main"
jobs:
  build-conda:
    name: Build Conda Python
    secrets: inherit
    uses: ./.github/workflows/conda-python-build.yaml
    with:
      build_type: branch
  test-conda:
    name: Test Conda Python
    needs: build-conda
    secrets: inherit
    uses: ./.github/workflows/conda-python-test.yaml
    with:
      build_type: branch
  build-wheels:
    name: Build Wheels
    secrets: inherit
    uses: ./.github/workflows/wheels-build.yaml
    with:
      build_type: branch
  test-wheels:
    name: Test Wheels
    needs: build-wheels
    secrets: inherit
    uses: ./.github/workflows/wheels-test.yaml
    with:
      build_type: branch
  build-docs:
    name: Build Docs
    needs:
      - test-conda
      - test-wheels
    secrets: inherit
    uses: ./.github/workflows/build-docs.yml
    with:
      is_release: true
      download_artifacts: true
